package Vista;

import CRUD.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class VistaCrud extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    int id;
    DefaultTableModel modelo;

    public VistaCrud() {
        initComponents();
        setLocationRelativeTo(null);
        Listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkHIJOS = new javax.swing.JCheckBox();
        slNOTA = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spinCANTIDAD = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMODIFICAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnELIMINAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNUEVO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAGREGAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNOMBRE = new javax.swing.JTextField();
        txtEDAD = new javax.swing.JTextField();
        txtSEXO = new javax.swing.JTextField();
        txtPESO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("A");

        jLabel10.setText("B");

        jLabel11.setText("C");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("BOTONES CRUD");

        jLabel1.setText("ID");

        btnMODIFICAR.setBackground(new java.awt.Color(0, 0, 204));
        btnMODIFICAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMODIFICAR.setForeground(new java.awt.Color(255, 255, 255));
        btnMODIFICAR.setText("MODIFICAR");
        btnMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMODIFICARActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE");

        btnELIMINAR.setBackground(new java.awt.Color(255, 51, 0));
        btnELIMINAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        btnELIMINAR.setText("ELIMINAR");
        btnELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELIMINARActionPerformed(evt);
            }
        });

        jLabel3.setText("EDAD");

        btnNUEVO.setBackground(new java.awt.Color(255, 255, 0));
        btnNUEVO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNUEVO.setText("NUEVO");
        btnNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNUEVOActionPerformed(evt);
            }
        });

        jLabel4.setText("SEXO");

        btnAGREGAR.setBackground(new java.awt.Color(102, 255, 0));
        btnAGREGAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAGREGAR.setForeground(new java.awt.Color(255, 255, 255));
        btnAGREGAR.setText("AGREGAR");
        btnAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAGREGARActionPerformed(evt);
            }
        });

        jLabel5.setText("PESO");

        jLabel6.setText("HIJOS");

        jLabel7.setText("CANTIDAD DE HIJOS");

        jLabel8.setText("NOTA");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMBREActionPerformed(evt);
            }
        });

        txtEDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEDADActionPerformed(evt);
            }
        });

        txtSEXO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSEXOActionPerformed(evt);
            }
        });

        txtPESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPESOActionPerformed(evt);
            }
        });

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "EDAD", "SEXO", "PESO", "HIJOS", "CANTIDAD", "NOTA"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chkHIJOS)
                                    .addComponent(txtPESO, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(spinCANTIDAD)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slNOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel10)
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel11)))
                                .addGap(21, 21, 21)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(btnNUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHIJOS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtEDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinCANTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slNOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMODIFICAR, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnNUEVO, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnAGREGAR, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMBREActionPerformed

    private void txtEDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEDADActionPerformed

    private void txtSEXOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSEXOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSEXOActionPerformed

    private void txtPESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPESOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPESOActionPerformed

    private void btnAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAGREGARActionPerformed
        Agregar();
        Listar();
        Nuevo();
    }//GEN-LAST:event_btnAGREGARActionPerformed

    private void btnNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNUEVOActionPerformed
        Nuevo();
    }//GEN-LAST:event_btnNUEVOActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        int fila = TablaDatos.getSelectedRow();
if (fila == -1) {
    JOptionPane.showMessageDialog(null, "FILA NO SELECCIONADA");
} else {
    id = Integer.parseInt(TablaDatos.getValueAt(fila, 0).toString());
    String nombre = TablaDatos.getValueAt(fila, 1).toString();
    String edad = TablaDatos.getValueAt(fila, 2).toString();
    String sexo = TablaDatos.getValueAt(fila, 3).toString();
    String peso = TablaDatos.getValueAt(fila, 4).toString();
    boolean hijo = Boolean.parseBoolean(TablaDatos.getValueAt(fila, 5).toString());
    int hijoscnt = Integer.parseInt(TablaDatos.getValueAt(fila, 6).toString());
    String nota = TablaDatos.getValueAt(fila, 7).toString();

    txtID.setText(String.valueOf(id));
    txtNOMBRE.setText(nombre);
    txtEDAD.setText(edad);
    txtSEXO.setText(sexo);
    txtPESO.setText(peso);
    chkHIJOS.setSelected(hijo);
    spinCANTIDAD.setValue(hijoscnt);

    // Convertir la nota de nuevo al valor del slider
    switch (nota) {
        case "A":
            slNOTA.setValue(0);
            break;
        case "B":
            slNOTA.setValue(5);
            break;
        case "C":
            slNOTA.setValue(10);
            break;
        default:
            slNOTA.setValue(0); // Valor por defecto si la nota no es A, B o C
    }
}


    }//GEN-LAST:event_TablaDatosMouseClicked

    private void btnMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMODIFICARActionPerformed
        Modificar();
        Listar();
        Nuevo();
    }//GEN-LAST:event_btnMODIFICARActionPerformed

    private void btnELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELIMINARActionPerformed
        Eliminar();
        Listar();
        Nuevo();
    }//GEN-LAST:event_btnELIMINARActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrud().setVisible(true);
            }
        });
    }

    //M E T O D O || L I S T A R
    public void Listar() {
        String sql = "SELECT*FROM practica;";

        try {
            cn = con.getConexion();
            st = cn.createStatement();
            rs = st.executeQuery(sql);

            Object[] usuario = new Object[8];
            modelo = (DefaultTableModel) TablaDatos.getModel();

            while (rs.next()) {
                usuario[0] = rs.getInt("id");
                usuario[1] = rs.getString("nombre");
                usuario[2] = rs.getInt("edad");
                usuario[3] = rs.getString("sexo");
                usuario[4] = rs.getString("peso");
                usuario[5] = rs.getString("hijos");
                usuario[6] = rs.getInt("hijoscant");
                usuario[7] = rs.getString("nota");

                modelo.addRow(usuario);
            }

            TablaDatos.setModel(modelo);

        } catch (Exception e) {
            System.out.println("ERROR EN EL METODO LISTAR" + e.toString());
        }
    }

    //M E T O D O || A G R E G A R
    public void Agregar() {
        String nombre = txtNOMBRE.getText();
        String edad = txtEDAD.getText();
        String sexo = txtSEXO.getText();
        String peso = txtPESO.getText();
        boolean hijos = chkHIJOS.isSelected();
        int cnthijos = (int) spinCANTIDAD.getValue();
        String nota;

        int sliderValue = slNOTA.getValue();
        if (sliderValue <= 3) {
            nota = "A";
        } else if (sliderValue <= 6) {
            nota = "B";
        } else {
            nota = "C";
        }

        if (nombre.equals("") || edad.equals("") || sexo.equals("") || peso.equals("") || Integer.toString(cnthijos).equals("") || nota.equals("")) {
            JOptionPane.showMessageDialog(null, "FALTAN VALORES");
        } else {
            {
                String sql = "INSERT INTO practica (nombre, edad, sexo, peso, hijos, hijoscant, nota) VALUES ('" + nombre + "', " + edad + ", '" + sexo + "', '" + peso + "', " + hijos + ", " + cnthijos + ", '" + nota + "');";

                try {
                    cn = con.getConexion();
                    st = cn.createStatement();
                    st.executeUpdate(sql);
                    System.out.println("SE AGREGO CORRECTAMENTE");
                    Limpiar();
                } catch (Exception e) {
                    System.out.println("NO SE LOGRO AGREGAR CORRECTAMENTE" + e.toString());
                }
            }
        }
    }

    public void Limpiar() {
        for (int i = 0; i < TablaDatos.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public void Nuevo() {
        txtID.setText("");
        txtNOMBRE.setText("");
        txtEDAD.setText("");
        txtSEXO.setText("");
        txtPESO.setText("");
        chkHIJOS.setSelected(false);
        spinCANTIDAD.setValue(0);
        slNOTA.setValue(0);
        txtNOMBRE.requestFocus();
    }

    //M E T O D O || M O D I F I C A R
     public void Modificar() {
        String nombre = txtNOMBRE.getText();
        String edad = txtEDAD.getText();
        String sexo = txtSEXO.getText();
        String peso = txtPESO.getText();
        boolean hijos = chkHIJOS.isSelected();
        int cnthijos = (int) spinCANTIDAD.getValue();
        String nota;

        int sliderValue = slNOTA.getValue();
        if (sliderValue <= 3) {
            nota = "A";
        } else if (sliderValue <= 6) {
            nota = "B";
        } else {
            nota = "C";
        }

        if (nombre.equals("") || edad.equals("") || sexo.equals("") || peso.equals("") || Integer.toString(cnthijos).equals("") || nota.equals("")) {
            JOptionPane.showMessageDialog(null, "FALTAN VALORES");
        } else {
            {
                String sql = "UPDATE practica SET nombre = '" + nombre + "', edad = '" + edad + "', sexo = '" + sexo + "', peso = '" + peso + "', hijos = '" + hijos + "', hijoscnat = '" + cnthijos + "', nota = '" + nota + "' WHERE id ="+id;

                try {
                    cn = con.getConexion();
                    st = cn.createStatement();
                    st.executeUpdate(sql);
                    System.out.println("SE MODIFICO CORRECTAMENTE");
                    Limpiar();
                } catch (Exception e) {
                    System.out.println("NO SE LOGRO MODIFICAR CORRECTAMENTE" + e.toString());
                }
            }
        }
    }
     
     
     public void Eliminar(){
     
     int fila = TablaDatos.getSelectedRow();
         if (fila == -1) {
             JOptionPane.showMessageDialog(null, "FILA NO SELECCIONADA");
             Limpiar();
         } else {
             String sql = "DELETE FROM practica WHERE id ="+id;
             try {
                 cn = con.getConexion();
                 st = cn.createStatement();
                 st.executeUpdate(sql);
                 System.out.println("SE ELIMINO CORRECTAMENTE");
                 Limpiar();
             } catch (Exception e) {
                 System.out.println("ERROR AL ELIMINAR");
             }
         }
     }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnAGREGAR;
    private javax.swing.JButton btnELIMINAR;
    private javax.swing.JButton btnMODIFICAR;
    private javax.swing.JButton btnNUEVO;
    private javax.swing.JCheckBox chkHIJOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider slNOTA;
    private javax.swing.JSpinner spinCANTIDAD;
    private javax.swing.JTextField txtEDAD;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtPESO;
    private javax.swing.JTextField txtSEXO;
    // End of variables declaration//GEN-END:variables

}
